<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Errors;

class ErrorResponse1Throwable extends \RuntimeException
{
    public ErrorResponse1 $container;

    public function __construct(string $message, int $statusCode, ErrorResponse1 $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}