<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Operations;

use Ding\DingSDK\Models\Errors;
use Ding\DingSDK\Models\Shared;
class FeedbackResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * Bad Request
     *
     * @var ?Errors\ErrorResponse $errorResponse
     */
    public ?Errors\ErrorResponse $errorResponse = null;

    /**
     * OK
     *
     * @var ?Shared\FeedbackResponse $feedbackResponse
     */
    public ?Shared\FeedbackResponse $feedbackResponse = null;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * @param  ?string  $contentType
     * @param  ?int  $statusCode
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  ?Errors\ErrorResponse  $errorResponse
     * @param  ?Shared\FeedbackResponse  $feedbackResponse
     */
    public function __construct(?string $contentType = null, ?int $statusCode = null, ?\Psr\Http\Message\ResponseInterface $rawResponse = null, ?Errors\ErrorResponse $errorResponse = null, ?Shared\FeedbackResponse $feedbackResponse = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->errorResponse = $errorResponse;
        $this->feedbackResponse = $feedbackResponse;
    }
}