<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Operations;

use Ding\DingSDK\Utils\SpeakeasyMetadata;
class GetAuthenticationStatusRequest
{
    /**
     *
     * @var string $authUuid
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=auth_uuid')]
    public string $authUuid;

    /**
     * @param  string  $authUuid
     */
    public function __construct(string $authUuid)
    {
        $this->authUuid = $authUuid;
    }
}