<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Operations;

use Ding\DingSDK\Utils\SpeakeasyMetadata;
class LookupRequest
{
    /**
     *
     * @var string $customerUuid
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=customer-uuid')]
    public string $customerUuid;

    /**
     *
     * @var string $phoneNumber
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=phone_number')]
    public string $phoneNumber;

    /**
     * @param  string  $customerUuid
     * @param  string  $phoneNumber
     */
    public function __construct(string $customerUuid, string $phoneNumber)
    {
        $this->customerUuid = $customerUuid;
        $this->phoneNumber = $phoneNumber;
    }
}