<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Operations;

use Ding\DingSDK\Utils\SpeakeasyMetadata;
class LookupRequest
{
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=customer-uuid')]
    public string $customerUuid;

    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=phone_number')]
    public string $phoneNumber;

    public function __construct()
    {
        $this->customerUuid = '';
        $this->phoneNumber = '';
    }
}