<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Operations;

use \ding\sdk\Utils\SpeakeasyMetadata;
class LookupRequest
{
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=customer-uuid')]
    public string $customerUuid;
    
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\ding\sdk\Models\Components\LookupRequest $lookupRequest = null;
    
	public function __construct()
	{
		$this->customerUuid = "";
		$this->lookupRequest = null;
	}
}
