<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Operations;


class LookupResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * Bad Request
     *
     * @var ?\Ding\DingSDK\Models\Shared\ErrorResponse $errorResponse
     */
    public ?\Ding\DingSDK\Models\Shared\ErrorResponse $errorResponse = null;

    /**
     * OK
     *
     * @var ?\Ding\DingSDK\Models\Shared\LookupResponse $lookupResponse
     */
    public ?\Ding\DingSDK\Models\Shared\LookupResponse $lookupResponse = null;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;

    public function __construct()
    {
        $this->contentType = '';
        $this->errorResponse = null;
        $this->lookupResponse = null;
        $this->statusCode = 0;
        $this->rawResponse = null;
    }
}