<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class Attempt
{
    /**
     * The attempt number.
     *
     * @var ?int $attemptNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempt_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $attemptNumber = null;

    /**
     * The capability of the attempt.
     *
     * @var ?Capability $capability
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capability')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\Capability|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Capability $capability = null;

    /**
     * The content of the attempt.
     *
     * @var ?string $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $content = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The ID of the attempt.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The sender ID of the attempt.
     *
     * @var ?string $senderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $senderId = null;

    /**
     * The status of the attempt. Possible values are:
     *
     *   * `pending` - The attempt is pending.
     *   * `delivered` - The attempt was delivered.
     *   * `failed` - The attempt failed.
     *   * `rate_limited` - The authentication was rate limited and cannot be retried.
     *   * `expired` - The authentication has expired and cannot be retried.
     *
     *
     * @var ?AuthenticationStatusResponseSchemasStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\AuthenticationStatusResponseSchemasStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthenticationStatusResponseSchemasStatus $status = null;

    /**
     * The type of the event.
     *
     * @var ?Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\Type|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Type $type = null;

    /**
     * @param  ?int  $attemptNumber
     * @param  ?Capability  $capability
     * @param  ?string  $content
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $id
     * @param  ?string  $senderId
     * @param  ?AuthenticationStatusResponseSchemasStatus  $status
     * @param  ?Type  $type
     */
    public function __construct(?int $attemptNumber = null, ?Capability $capability = null, ?string $content = null, ?\DateTime $createdAt = null, ?string $id = null, ?string $senderId = null, ?AuthenticationStatusResponseSchemasStatus $status = null, ?Type $type = null)
    {
        $this->attemptNumber = $attemptNumber;
        $this->capability = $capability;
        $this->content = $content;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->senderId = $senderId;
        $this->status = $status;
        $this->type = $type;
    }
}