<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class AuthenticationStatusResponse
{
    /**
     * A unique, user-defined identifier that will be included in webhook events.
     *
     * @var ?string $correlationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('correlation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $correlationId = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Represents a collection of events that occur during the authentication process. Each event captures specific actions and outcomes related to the authentication attempts, checks, delivery statuses, and balance updates. The array can contain different types of events, each with its own structure and properties.
     *
     * @var ?array<mixed> $events
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
    #[\Speakeasy\Serializer\Annotation\Type('array<mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $events = null;

    /**
     * An E.164 formatted phone number.
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * [Signals](/guides/prevent-fraud#signals) are data points used to distinguish between fraudulent and legitimate users.
     *
     * @var ?Signals $signals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signals')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\Signals|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Signals $signals = null;

    /**
     * The template id associated with the message content variant to be sent.
     *
     * @var ?string $templateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $templateId = null;

    /**
     * The UUID of the corresponding authentication.
     *
     * @var ?string $uuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uuid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $uuid = null;

    /**
     * @param  ?string  $correlationId
     * @param  ?\DateTime  $createdAt
     * @param  ?array<mixed>  $events
     * @param  ?string  $phoneNumber
     * @param  ?Signals  $signals
     * @param  ?string  $templateId
     * @param  ?string  $uuid
     */
    public function __construct(?string $correlationId = null, ?\DateTime $createdAt = null, ?array $events = null, ?string $phoneNumber = null, ?Signals $signals = null, ?string $templateId = null, ?string $uuid = null)
    {
        $this->correlationId = $correlationId;
        $this->createdAt = $createdAt;
        $this->events = $events;
        $this->phoneNumber = $phoneNumber;
        $this->signals = $signals;
        $this->templateId = $templateId;
        $this->uuid = $uuid;
    }
}