<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** The type of device the user is using. */
enum AuthenticationStatusResponseDeviceType: string
{
    case Ios = 'IOS';
    case Android = 'ANDROID';
    case Web = 'WEB';
}
