<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** The type of the event. */
enum AuthenticationStatusResponseSchemasEventsType: string
{
    case Attempt = 'attempt';
    case Check = 'check';
    case DeliveryStatus = 'delivery_status';
    case BalanceUpdate = 'balance_update';
}
