<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/**
 * The status of the attempt. Possible values are:
 *
 *   * `pending` - The attempt is pending.
 *   * `delivered` - The attempt was delivered.
 *   * `failed` - The attempt failed.
 *   * `rate_limited` - The authentication was rate limited and cannot be retried.
 *   * `expired` - The authentication has expired and cannot be retried.
 *
 */
enum AuthenticationStatusResponseSchemasStatus: string
{
    case Pending = 'pending';
    case Delivered = 'delivered';
    case Failed = 'failed';
    case RateLimited = 'rate_limited';
    case Expired = 'expired';
}
