<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/**
 * The status of the delivery. Possible values are:
 *
 *   * `unknown` - The status of the delivery is unknown.
 *   * `submitted` - The message has been submitted to the carrier.
 *   * `in_transit` - The message is in transit to the recipient.
 *   * `delivered` - The message has been delivered to the recipient.
 *   * `undeliverable` - The message could not be delivered to the recipient.
 *
 */
enum AuthenticationStatusResponseStatus: string
{
    case Unknown = 'unknown';
    case Submitted = 'submitted';
    case InTransit = 'in_transit';
    case Delivered = 'delivered';
    case Undeliverable = 'undeliverable';
}
