<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


enum BalanceUpdateType: string
{
    case Unknown = 'unknown';
    case Authentication = 'authentication';
    case Attempt = 'attempt';
    case AttemptPending = 'attempt_pending';
    case AttemptSuccess = 'attempt_success';
    case AuthenticationPending = 'authentication_pending';
    case AuthenticationSuccess = 'authentication_success';
}
