<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** The capability of the attempt. */
enum Capability: string
{
    case Rcs = 'rcs';
    case Text = 'text';
    case Whatsapp = 'whatsapp';
    case Viber = 'viber';
}
