<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class Check
{
    /**
     * The code that was checked.
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The ID of the check.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?CheckStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\CheckStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CheckStatus $status = null;

    /**
     * The type of the event.
     *
     * @var ?AuthenticationStatusResponseType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\AuthenticationStatusResponseType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthenticationStatusResponseType $type = null;

    /**
     * @param  ?string  $code
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $id
     * @param  ?CheckStatus  $status
     * @param  ?AuthenticationStatusResponseType  $type
     */
    public function __construct(?string $code = null, ?\DateTime $createdAt = null, ?string $id = null, ?CheckStatus $status = null, ?AuthenticationStatusResponseType $type = null)
    {
        $this->code = $code;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->status = $status;
        $this->type = $type;
    }
}