<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** A machine-readable code that describes the error. */
enum Code: string
{
    case AccountInvalid = 'account_invalid';
    case AppRealmRequireDeviceType = 'app_realm_require_device_type';
    case BadRequest = 'bad_request';
    case BlockedNumber = 'blocked_number';
    case DuplicatedFeedbackStatus = 'duplicated_feedback_status';
    case InternalServerError = 'internal_server_error';
    case InvalidAppRealm = 'invalid_app_realm';
    case InvalidAppVersion = 'invalid_app_version';
    case InvalidAuthUuid = 'invalid_auth_uuid';
    case InvalidDeviceId = 'invalid_device_id';
    case InvalidDeviceModel = 'invalid_device_model';
    case InvalidFeedbackStatus = 'invalid_feedback_status';
    case InvalidLine = 'invalid_line';
    case InvalidOsVersion = 'invalid_os_version';
    case InvalidPhoneNumber = 'invalid_phone_number';
    case InvalidSenderId = 'invalid_sender_id';
    case InvalidTemplateId = 'invalid_template_id';
    case NegativeBalance = 'negative_balance';
    case NoAssociatedAuthFound = 'no_associated_auth_found';
    case SuspendedAccount = 'suspended_account';
    case UnauthorizedSenderId = 'unauthorized_sender_id';
    case UnsupportedAppRealmDeviceType = 'unsupported_app_realm_device_type';
    case UnsupportedRegion = 'unsupported_region';
}
