<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Shared;


/**
 * A machine-readable code that describes the error. Possible values are:
 * 
 *   * `invalid_phone_number` - This is not a valid E.164 number.
 *   * `internal_server_error` - An internal server error occurred.
 *   * `bad_request` - The request was malformed.
 *   * `account_invalid` - The customer UUID you provided is invalid.
 *   * `negative_balance` - You have a negative balance.
 *   * `invalid_line` - Ding does not support this type of phone number.
 *   * `unsupported_region` - Ding does not support this region yet.
 *   * `invalid_auth_uuid` - The authentication UUID you provided is invalid.
 *   * `blocked_number` - The phone number you provided is in the blocklist.
 *   * `invalid_app_version` - The app version you provided is invalid.
 *   * `invalid_os_version` - The OS version you provided is invalid.
 *   * `invalid_device_model` - The device model you provided is invalid.
 *   * `invalid_device_id` - The device ID you provided is invalid.
 * 
 */
enum Code: string
{
    case InvalidPhoneNumber = 'invalid_phone_number';
    case InternalServerError = 'internal_server_error';
    case BadRequest = 'bad_request';
    case AccountInvalid = 'account_invalid';
    case NegativeBalance = 'negative_balance';
    case InvalidLine = 'invalid_line';
    case UnsupportedRegion = 'unsupported_region';
    case InvalidAuthUuid = 'invalid_auth_uuid';
    case InvalidAppRealm = 'invalid_app_realm';
    case UnsupportedAppRealmDeviceType = 'unsupported_app_realm_device_type';
    case AppRealmRequireDeviceType = 'app_realm_require_device_type';
    case BlockedNumber = 'blocked_number';
    case InvalidAppVersion = 'invalid_app_version';
    case InvalidOsVersion = 'invalid_os_version';
    case InvalidDeviceModel = 'invalid_device_model';
    case InvalidDeviceId = 'invalid_device_id';
}
