<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** CreateAuthenticationResponse - A successful response to an authentication creation request. */
class CreateAuthenticationResponse
{
    /**
     * A unique identifier for the authentication that you can use on the /check and /retry endpoints.
     *
     * @var ?string $authenticationUuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authentication_uuid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authenticationUuid = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The time at which the authentication expires and can no longer be checked or retried.
     *
     * @var ?\DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $expiresAt = null;

    /**
     * The status of the authentication. Possible values are:
     *
     *   * `pending` - The OTP code is being sent.
     *   * `rate_limited` - This user is rate-limited and cannot receive another code.
     *   * `spam_detected` - This attempt is flagged as spam. Go to the dashboard for more details.
     *
     *
     * @var ?Status $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\Status|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Status $status = null;

    /**
     * @param  ?string  $authenticationUuid
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $expiresAt
     * @param  ?Status  $status
     */
    public function __construct(?string $authenticationUuid = null, ?\DateTime $createdAt = null, ?\DateTime $expiresAt = null, ?Status $status = null)
    {
        $this->authenticationUuid = $authenticationUuid;
        $this->createdAt = $createdAt;
        $this->expiresAt = $expiresAt;
        $this->status = $status;
    }
}