<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class CreateCheckResponse
{
    /**
     * The UUID of the corresponding authentication.
     *
     * @var ?string $authenticationUuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('authentication_uuid')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $authenticationUuid = null;

    /**
     * The status of the check. Possible values are:
     *
     *   * `valid` - The code is valid.
     *   * `invalid` - The code is invalid.
     *   * `without_attempt` - No attempt was sent yet, so a check cannot be completed.
     *   * `rate_limited` - The authentication was rate limited and cannot be checked.
     *   * `already_validated` - The authentication has already been validated.
     *   * `expired_auth` - The authentication has expired and cannot be checked.
     *
     *
     * @var ?CreateCheckResponseStatus $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\CreateCheckResponseStatus|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?CreateCheckResponseStatus $status = null;

    /**
     * @param  ?string  $authenticationUuid
     * @param  ?CreateCheckResponseStatus  $status
     */
    public function __construct(?string $authenticationUuid = null, ?CreateCheckResponseStatus $status = null)
    {
        $this->authenticationUuid = $authenticationUuid;
        $this->status = $status;
    }
}