<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class CreateAuthenticationRequest
{
    /**
     * The Android SMS Retriever API hash code that identifies your app. This allows you to automatically retrieve and fill the OTP code on Android devices.
     *
     * @var ?string $appRealm
     */
    #[\JMS\Serializer\Annotation\SerializedName('app_realm')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $appRealm = null;

    /**
     * The version of your application.
     *
     * @var ?string $appVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('app_version')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $appVersion = null;

    /**
     * A webhook URL to which delivery statuses will be sent.
     *
     * @var ?string $callbackUrl
     */
    #[\JMS\Serializer\Annotation\SerializedName('callback_url')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $callbackUrl = null;

    /**
     * A unique, user-defined identifier that will be included in webhook events
     *
     * @var ?string $correlationId
     */
    #[\JMS\Serializer\Annotation\SerializedName('correlation_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $correlationId = null;

    /**
     * Your customer UUID, which can be found in the API settings in the dashboard.
     *
     * @var string $customerUuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('customer_uuid')]
    public string $customerUuid;

    /**
     * Unique identifier for the user's device. For Android, this corresponds to the `ANDROID_ID` and for iOS, this corresponds to the `identifierForVendor`.
     *
     * @var ?string $deviceId
     */
    #[\JMS\Serializer\Annotation\SerializedName('device_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $deviceId = null;

    /**
     * The model of the user's device.
     *
     * @var ?string $deviceModel
     */
    #[\JMS\Serializer\Annotation\SerializedName('device_model')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $deviceModel = null;

    /**
     * The type of device the user is using.
     *
     * @var ?DeviceType $deviceType
     */
    #[\JMS\Serializer\Annotation\SerializedName('device_type')]
    #[\JMS\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\DeviceType')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DeviceType $deviceType = null;

    /**
     * The IP address of the user's device.
     *
     * @var ?string $ip
     */
    #[\JMS\Serializer\Annotation\SerializedName('ip')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ip = null;

    /**
     * This signal should do more than just confirm if a user is returning to your app; it should provide a higher level of trust, indicating that the user is genuine. For more details, refer to [Signals](/guides/prevent-fraud#signals).
     *
     * @var ?bool $isReturningUser
     */
    #[\JMS\Serializer\Annotation\SerializedName('is_returning_user')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isReturningUser = null;

    /**
     * The version of the user's device operating system.
     *
     * @var ?string $osVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('os_version')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $osVersion = null;

    /**
     * An E.164 formatted phone number to send the OTP to.
     *
     * @var string $phoneNumber
     */
    #[\JMS\Serializer\Annotation\SerializedName('phone_number')]
    public string $phoneNumber;

    /**
     * The template id associated with the message content variant to be sent.
     *
     * @var ?string $templateId
     */
    #[\JMS\Serializer\Annotation\SerializedName('template_id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $templateId = null;

    /**
     * @param  ?string  $customerUuid
     * @param  ?string  $phoneNumber
     * @param  ?string  $appRealm
     * @param  ?string  $appVersion
     * @param  ?string  $callbackUrl
     * @param  ?string  $correlationId
     * @param  ?string  $deviceId
     * @param  ?string  $deviceModel
     * @param  ?DeviceType  $deviceType
     * @param  ?string  $ip
     * @param  ?bool  $isReturningUser
     * @param  ?string  $osVersion
     * @param  ?string  $templateId
     */
    public function __construct(?string $customerUuid = null, ?string $phoneNumber = null, ?string $appRealm = null, ?string $appVersion = null, ?string $callbackUrl = null, ?string $correlationId = null, ?string $deviceId = null, ?string $deviceModel = null, ?DeviceType $deviceType = null, ?string $ip = null, ?bool $isReturningUser = null, ?string $osVersion = null, ?string $templateId = null)
    {
        $this->customerUuid = $customerUuid;
        $this->phoneNumber = $phoneNumber;
        $this->appRealm = $appRealm;
        $this->appVersion = $appVersion;
        $this->callbackUrl = $callbackUrl;
        $this->correlationId = $correlationId;
        $this->deviceId = $deviceId;
        $this->deviceModel = $deviceModel;
        $this->deviceType = $deviceType;
        $this->ip = $ip;
        $this->isReturningUser = $isReturningUser;
        $this->osVersion = $osVersion;
        $this->templateId = $templateId;
    }
}