<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class CreateAuthenticationRequest
{
    /**
     * The Android SMS Retriever API hash code that identifies your app. This allows you to automatically retrieve and fill the OTP code on Android devices.
     *
     * @var ?string $appRealm
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('app_realm')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $appRealm = null;

    /**
     * The version of your application.
     *
     * @var ?string $appVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('app_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $appVersion = null;

    /**
     * A webhook URL to which delivery statuses will be sent.
     *
     * @var ?string $callbackUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('callback_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $callbackUrl = null;

    /**
     * A unique, user-defined identifier that will be included in webhook events
     *
     * @var ?string $correlationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('correlation_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $correlationId = null;

    /**
     * Your customer UUID, which can be found in the API settings in the dashboard.
     *
     * @var string $customerUuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_uuid')]
    public string $customerUuid;

    /**
     * Unique identifier for the user's device. For Android, this corresponds to the `ANDROID_ID` and for iOS, this corresponds to the `identifierForVendor`.
     *
     * @var ?string $deviceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceId = null;

    /**
     * The model of the user's device.
     *
     * @var ?string $deviceModel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_model')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceModel = null;

    /**
     * The type of device the user is using.
     *
     * @var ?DeviceType $deviceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\DeviceType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DeviceType $deviceType = null;

    /**
     * The IP address of the user's device.
     *
     * @var ?string $ip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ip = null;

    /**
     * This signal should do more than just confirm if a user is returning to your app; it should provide a higher level of trust, indicating that the user is genuine. For more details, refer to [Signals](/guides/prevent-fraud#signals).
     *
     * @var ?bool $isReturningUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_returning_user')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isReturningUser = null;

    /**
     * A BCP-47 locale indicating the language the SMS should be sent to; if this is not set, the SMS will be sent to the language specified by the country code of the message. If we don't support the language set, the message will be sent in US English (en-US).
     *
     * @var ?string $locale
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locale')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locale = null;

    /**
     * The version of the user's device operating system.
     *
     * @var ?string $osVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('os_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $osVersion = null;

    /**
     * An E.164 formatted phone number to send the OTP to.
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone_number')]
    public string $phoneNumber;

    /**
     * The Sender ID to use when sending the message.
     *
     * @var ?string $senderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $senderId = null;

    /**
     * The template id associated with the message content variant to be sent.
     *
     * @var ?string $templateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $templateId = null;

    /**
     * @param  string  $customerUuid
     * @param  string  $phoneNumber
     * @param  ?string  $appRealm
     * @param  ?string  $appVersion
     * @param  ?string  $callbackUrl
     * @param  ?string  $correlationId
     * @param  ?string  $deviceId
     * @param  ?string  $deviceModel
     * @param  ?DeviceType  $deviceType
     * @param  ?string  $ip
     * @param  ?bool  $isReturningUser
     * @param  ?string  $locale
     * @param  ?string  $osVersion
     * @param  ?string  $senderId
     * @param  ?string  $templateId
     */
    public function __construct(string $customerUuid, string $phoneNumber, ?string $appRealm = null, ?string $appVersion = null, ?string $callbackUrl = null, ?string $correlationId = null, ?string $deviceId = null, ?string $deviceModel = null, ?DeviceType $deviceType = null, ?string $ip = null, ?bool $isReturningUser = null, ?string $locale = null, ?string $osVersion = null, ?string $senderId = null, ?string $templateId = null)
    {
        $this->customerUuid = $customerUuid;
        $this->phoneNumber = $phoneNumber;
        $this->appRealm = $appRealm;
        $this->appVersion = $appVersion;
        $this->callbackUrl = $callbackUrl;
        $this->correlationId = $correlationId;
        $this->deviceId = $deviceId;
        $this->deviceModel = $deviceModel;
        $this->deviceType = $deviceType;
        $this->ip = $ip;
        $this->isReturningUser = $isReturningUser;
        $this->locale = $locale;
        $this->osVersion = $osVersion;
        $this->senderId = $senderId;
        $this->templateId = $templateId;
    }
}