<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class CreateCheckResponse
{
    /**
     * The UUID of the corresponding authentication.
     *
     * @var ?string $authenticationUuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authentication_uuid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authenticationUuid = null;

    /**
     *
     * @var ?CheckStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\CheckStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CheckStatus $status = null;

    /**
     * @param  ?string  $authenticationUuid
     * @param  ?CheckStatus  $status
     */
    public function __construct(?string $authenticationUuid = null, ?CheckStatus $status = null)
    {
        $this->authenticationUuid = $authenticationUuid;
        $this->status = $status;
    }
}