<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class DeliveryStatus
{
    /**
     * The ID of the attempt.
     *
     * @var ?string $attemptId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempt_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $attemptId = null;

    /**
     * The attempt number.
     *
     * @var ?int $attemptNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempt_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $attemptNumber = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The status of the delivery. Possible values are:
     *
     *   * `unknown` - The status of the delivery is unknown.
     *   * `submitted` - The message has been submitted to the carrier.
     *   * `in_transit` - The message is in transit to the recipient.
     *   * `delivered` - The message has been delivered to the recipient.
     *   * `undeliverable` - The message could not be delivered to the recipient.
     *
     *
     * @var ?AuthenticationStatusResponseStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\AuthenticationStatusResponseStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthenticationStatusResponseStatus $status = null;

    /**
     * The type of the event.
     *
     * @var ?AuthenticationStatusResponseSchemasType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\AuthenticationStatusResponseSchemasType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthenticationStatusResponseSchemasType $type = null;

    /**
     * @param  ?string  $attemptId
     * @param  ?int  $attemptNumber
     * @param  ?\DateTime  $createdAt
     * @param  ?AuthenticationStatusResponseStatus  $status
     * @param  ?AuthenticationStatusResponseSchemasType  $type
     */
    public function __construct(?string $attemptId = null, ?int $attemptNumber = null, ?\DateTime $createdAt = null, ?AuthenticationStatusResponseStatus $status = null, ?AuthenticationStatusResponseSchemasType $type = null)
    {
        $this->attemptId = $attemptId;
        $this->attemptNumber = $attemptNumber;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->type = $type;
    }
}