<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class FeedbackRequest
{
    /**
     * Your customer UUID, which can be found in the API settings in the dashboard.
     *
     * @var string $customerUuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('customer_uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $customerUuid;

    /**
     * An E.164 formatted phone number.
     *
     * @var string $phoneNumber
     */
    #[\JMS\Serializer\Annotation\SerializedName('phone_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phoneNumber;

    /**
     * The type of the feedback.
     *
     * @var \Ding\DingSDK\Models\Shared\FeedbackRequestStatus $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<Ding\DingSDK\Models\Shared\FeedbackRequestStatus>')]
    public FeedbackRequestStatus $status;

    public function __construct()
    {
        $this->customerUuid = '';
        $this->phoneNumber = '';
        $this->status = \Ding\DingSDK\Models\Shared\FeedbackRequestStatus::Onboarded;
    }
}