<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class FeedbackResponse
{
    /**
     * The UUID of the feedback.
     *
     * @var ?string $uuid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uuid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $uuid = null;

    /**
     * @param  ?string  $uuid
     */
    public function __construct(?string $uuid = null)
    {
        $this->uuid = $uuid;
    }
}