<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class FeedbackResponse
{
    /**
     * The UUID of the feedback.
     *
     * @var ?string $uuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $uuid = null;

    public function __construct()
    {
        $this->uuid = null;
    }
}