<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** The type of the feedback. */
enum FeedbackRequestStatus: string
{
    case Onboarded = 'onboarded';
    case NotOnboarded = 'not_onboarded';
}
