<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Shared;


/** The type of phone line. */
enum LineType: string
{
    case FixedLine = 'FixedLine';
    case Mobile = 'Mobile';
    case TollFree = 'TollFree';
    case PremiumRate = 'PremiumRate';
    case SharedCost = 'SharedCost';
    case Voip = 'Voip';
    case Pager = 'Pager';
    case VoiceMail = 'VoiceMail';
    case UniversalAccess = 'UniversalAccess';
    case Service = 'Service';
    case Unknown = 'Unknown';
}
