<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class LookupResponse
{
    /**
     * The carrier of the phone number.
     *
     * @var ?string $carrier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('carrier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $carrier = null;

    /**
     * The ISO 3166-1 alpha-2 country code of the phone number.
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryCode = null;

    /**
     * The type of phone line.
     *
     *   * `CallingCards` - Numbers that are associated with providers of pre-paid domestic and international calling cards.
     *   * `FixedLine` - Landline phone numbers.
     *   * `InternetServiceProvider` - Numbers reserved for ISPs.
     *   * `LocalRate` - Numbers that can be assigned non-geographically.
     *   * `Mobile` - Mobile phone numbers.
     *   * `Other` - Other types of services.
     *   * `Pager` - Number ranges specifically allocated to paging devices.
     *   * `PayPhone` - Allocated numbers for payphone kiosks in some countries.
     *   * `PremiumRate` - Landline numbers where the calling party pays more than standard.
     *   * `Satellite` - Satellite phone numbers.
     *   * `Service` - Automated applications.
     *   * `SharedCost` - Specific landline ranges where the cost of making the call is shared between the calling and called party.
     *   * `ShortCodesCommercial` - Short codes are memorable, easy-to-use numbers, like the UK's NHS 111, often sold to businesses. Not available in all countries.
     *   * `TollFree` - Number where the called party pays for the cost of the call not the calling party.
     *   * `UniversalAccess` - Number ranges reserved for Universal Access initiatives.
     *   * `Unknown` - Unknown phone number type.
     *   * `VPN` - Numbers are used exclusively within a private telecommunications network, connecting the operator's terminals internally and not accessible via the public telephone network.
     *   * `VoiceMail` - A specific category of Interactive Voice Response (IVR) services.
     *   * `Voip` - Specific ranges for providers of VoIP services to allow incoming calls from the regular telephony network.
     *
     *
     * @var ?LineType $lineType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\LineType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LineType $lineType = null;

    /**
     * The mobile country code of the phone number.
     *
     * @var ?string $mcc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mcc')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mcc = null;

    /**
     * The mobile network code of the phone number.
     *
     * @var ?string $mnc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mnc')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mnc = null;

    /**
     * Whether the phone number has been ported.
     *
     * @var ?bool $numberPorted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number_ported')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $numberPorted = null;

    /**
     * An E.164 formatted phone number.
     *
     * @var ?string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phoneNumber = null;

    /**
     * @param  ?string  $carrier
     * @param  ?string  $countryCode
     * @param  ?LineType  $lineType
     * @param  ?string  $mcc
     * @param  ?string  $mnc
     * @param  ?bool  $numberPorted
     * @param  ?string  $phoneNumber
     */
    public function __construct(?string $carrier = null, ?string $countryCode = null, ?LineType $lineType = null, ?string $mcc = null, ?string $mnc = null, ?bool $numberPorted = null, ?string $phoneNumber = null)
    {
        $this->carrier = $carrier;
        $this->countryCode = $countryCode;
        $this->lineType = $lineType;
        $this->mcc = $mcc;
        $this->mnc = $mnc;
        $this->numberPorted = $numberPorted;
        $this->phoneNumber = $phoneNumber;
    }
}