<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Shared;


/** The status of the authentication. */
enum RetryAuthenticationResponseStatus: string
{
    case Approved = 'approved';
    case Denied = 'denied';
    case NoAttempt = 'no_attempt';
    case RateLimited = 'rate_limited';
    case ExpiredAuth = 'expired_auth';
    case AlreadyValidated = 'already_validated';
}
