<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Shared;


class RetryAuthenticationResponse
{
    /**
     * The UUID of the corresponding authentication.
     * 
     * @var ?string $authenticationUuid
     */
	#[\JMS\Serializer\Annotation\SerializedName('authentication_uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $authenticationUuid = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * The time at which the next retry will be available.
     * 
     * @var ?\DateTime $nextRetryAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('next_retry_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $nextRetryAt = null;
    
    /**
     * The number of retries remaining.
     * 
     * @var ?int $remainingRetry
     */
	#[\JMS\Serializer\Annotation\SerializedName('remaining_retry')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $remainingRetry = null;
    
    /**
     * The status of the authentication.
     * 
     * @var ?\ding\sdk\Models\Shared\RetryAuthenticationResponseStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<ding\sdk\Models\Shared\RetryAuthenticationResponseStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?RetryAuthenticationResponseStatus $status = null;
    
	public function __construct()
	{
		$this->authenticationUuid = null;
		$this->createdAt = null;
		$this->nextRetryAt = null;
		$this->remainingRetry = null;
		$this->status = null;
	}
}
