<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


class RetryAuthenticationRequest
{
    /**
     * The authentication UUID that was returned when you created the authentication.
     *
     * @var string $authenticationUuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('authentication_uuid')]
    public string $authenticationUuid;

    /**
     * Your customer UUID, which can be found in the API settings in the dashboard.
     *
     * @var string $customerUuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('customer_uuid')]
    public string $customerUuid;

    /**
     * @param  string  $authenticationUuid
     * @param  string  $customerUuid
     */
    public function __construct(string $authenticationUuid, string $customerUuid)
    {
        $this->authenticationUuid = $authenticationUuid;
        $this->customerUuid = $customerUuid;
    }
}