<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;

use Ding\DingSDK\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $apiKey
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=x-api-key')]
    public string $apiKey;

    /**
     * @param  ?string  $apiKey
     */
    public function __construct(?string $apiKey = null)
    {
        $this->apiKey = $apiKey;
    }
}