<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/** Signals - [Signals](/guides/prevent-fraud#signals) are data points used to distinguish between fraudulent and legitimate users. */
class Signals
{
    /**
     * The Android SMS Retriever API hash code that identifies your app. This allows you to automatically retrieve and fill the OTP code on Android devices.
     *
     * @var ?string $appRealm
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('app_realm')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $appRealm = null;

    /**
     * The version of your application.
     *
     * @var ?string $appVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('app_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $appVersion = null;

    /**
     * Unique identifier for the user's device. For Android, this corresponds to the `ANDROID_ID` and for iOS, this corresponds to the `identifierForVendor`.
     *
     * @var ?string $deviceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceId = null;

    /**
     * The model of the user's device.
     *
     * @var ?string $deviceModel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_model')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $deviceModel = null;

    /**
     * The type of device the user is using.
     *
     * @var ?AuthenticationStatusResponseDeviceType $deviceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Ding\DingSDK\Models\Shared\AuthenticationStatusResponseDeviceType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthenticationStatusResponseDeviceType $deviceType = null;

    /**
     * The IP address of the user's device.
     *
     * @var ?string $ip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ip = null;

    /**
     * This signal should do more than just confirm if a user is returning to your app; it should provide a higher level of trust, indicating that the user is genuine. For more details, refer to [Signals](/guides/prevent-fraud#signals).
     *
     * @var ?bool $isReturningUser
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_returning_user')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isReturningUser = null;

    /**
     * The version of the user's device operating system.
     *
     * @var ?string $osVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('os_version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $osVersion = null;

    /**
     * @param  ?string  $appRealm
     * @param  ?string  $appVersion
     * @param  ?string  $deviceId
     * @param  ?string  $deviceModel
     * @param  ?AuthenticationStatusResponseDeviceType  $deviceType
     * @param  ?string  $ip
     * @param  ?bool  $isReturningUser
     * @param  ?string  $osVersion
     */
    public function __construct(?string $appRealm = null, ?string $appVersion = null, ?string $deviceId = null, ?string $deviceModel = null, ?AuthenticationStatusResponseDeviceType $deviceType = null, ?string $ip = null, ?bool $isReturningUser = null, ?string $osVersion = null)
    {
        $this->appRealm = $appRealm;
        $this->appVersion = $appVersion;
        $this->deviceId = $deviceId;
        $this->deviceModel = $deviceModel;
        $this->deviceType = $deviceType;
        $this->ip = $ip;
        $this->isReturningUser = $isReturningUser;
        $this->osVersion = $osVersion;
    }
}