<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Ding\DingSDK\Models\Shared;


/**
 * The status of the authentication. Possible values are:
 *
 *   * `pending` - The OTP code is being sent.
 *   * `rate_limited` - This user is rate-limited and cannot receive another code.
 *   * `spam_detected` - This attempt is flagged as spam. Go to the dashboard for more details.
 *
 */
enum Status: string
{
    case Pending = 'pending';
    case RateLimited = 'rate_limited';
    case SpamDetected = 'spam_detected';
}
