<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Components;


/**
 * CreateAuthenticationResponse - A successful response to an authentication creation request.
 * 
 * @package ding\sdk\Models\Components
 * @access public
 */
class CreateAuthenticationResponse
{
    /**
     * A unique identifier for the authentication that you can use on the /check and /retry endpoints.
     * 
     * @var ?string $authenticationUuid
     */
	#[\JMS\Serializer\Annotation\SerializedName('authentication_uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $authenticationUuid = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * The time at which the authentication expires and can no longer be checked or retried.
     * 
     * @var ?\DateTime $expiresAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('expires_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiresAt = null;
    
    /**
     * The status of the authentication.
     * 
     * @var ?\ding\sdk\Models\Components\Status $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<ding\sdk\Models\Components\Status>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Status $status = null;
    
	public function __construct()
	{
		$this->authenticationUuid = null;
		$this->createdAt = null;
		$this->expiresAt = null;
		$this->status = null;
	}
}
