<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk\Models\Components;


/** A status representing the result of the check. */
enum CreateCheckResponseStatus: string
{
    case Valid = 'valid';
    case Invalid = 'invalid';
    case WithoutAttempt = 'without_attempt';
    case RateLimited = 'rate_limited';
    case AlreadyValidated = 'already_validated';
    case ExpiredAuth = 'expired_auth';
}
