<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ding\sdk;

class Lookup 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Lookup a phone number
     * 
     * @param string $customerUuid
     * @param ?\ding\sdk\Models\Components\LookupRequest $lookupRequest
     * @return \ding\sdk\Models\Operations\LookupResponse
     */
	public function lookup(
        string $customerUuid,
        ?\ding\sdk\Models\Components\LookupRequest $lookupRequest = null,
    ): \ding\sdk\Models\Operations\LookupResponse
    {
        $request = new \ding\sdk\Models\Operations\LookupRequest();
        $request->customerUuid = $customerUuid;
        $request->lookupRequest = $lookupRequest;
        
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/lookup');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "lookupRequest", "json");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \ding\sdk\Models\Operations\LookupResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->lookupResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'ding\sdk\Models\Components\LookupResponse', 'json');
            }
        }
        else if ($httpResponse->getStatusCode() === 400) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->errorResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'ding\sdk\Models\Components\ErrorResponse', 'json');
            }
        }

        return $response;
    }
}